"""Chart generation tool: runs a read-only SQL query and renders the result as
a bar, line, or pie chart image (PNG), returning a downloadable link.

Mirrors tools/export_tools.py and tools/er_diagram_tools.py's pattern: its own
directory, its own opportunistic TTL cleanup, and its own plain
(unauthenticated) Starlette download route mounted in server.py at
GET /charts/{file_id}.
"""
import re
import time
import uuid
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from starlette.requests import Request
from starlette.responses import FileResponse, JSONResponse, Response

from config import settings
from db_utils import fetch_all
from mcp_instance import mcp
from security import classify_statement

CHART_DIR = Path(settings.CHART_DIR)
CHART_DIR.mkdir(parents=True, exist_ok=True)

# Only ever generated by uuid.uuid4().hex, so this is just a defensive check
# against path traversal / unexpected characters before touching the filesystem.
_SAFE_FILE_ID_RE = re.compile(r"^[a-f0-9]{32}\.png$")

_VALID_CHART_TYPES = {"bar", "line", "pie"}
# Kept low (vs. MAX_ROWS_RETURNED/MAX_EXPORT_ROWS) since a chart with more
# bars/slices than this stops being readable - callers should aggregate/LIMIT
# the SQL to a sensible number of categories instead of relying on this cap.
_MAX_CHART_ROWS = 100

_CHART_COLOR = "#2563eb"


def _cleanup_expired() -> None:
    """Delete chart files older than CHART_TTL_SECONDS. Best-effort, called
    opportunistically before writing a new chart (no background task/thread)."""
    cutoff = time.time() - settings.CHART_TTL_SECONDS
    for path in CHART_DIR.glob("*"):
        try:
            if path.is_file() and path.stat().st_mtime < cutoff:
                path.unlink()
        except OSError:
            pass


def _build_download_url(file_name: str) -> str:
    base = settings.EXPORT_PUBLIC_BASE_URL.rstrip("/")
    return f"{base}/charts/{file_name}"


@mcp.tool()
def generate_chart(
    sql: str,
    chart_type: str,
    title: str,
    x_label: str | None = None,
    y_label: str | None = None,
) -> dict:
    """Execute a read-only (DQL) SQL query and render its result as a chart
    image (PNG), returning a downloadable `download_url`. Use this whenever the
    user explicitly asks for a chart, graph, or visual - e.g. "show me a bar
    chart of monthly signups", "pie chart of orders by category", "graph
    comparing this year's traffic to last year's".

    `chart_type` must be exactly one of "bar", "line", "pie":
    - "bar" / "line": the query's FIRST returned column is the x-axis
      (category or time period), the SECOND is the numeric y-axis value.
    - "pie": the FIRST column is the slice label, the SECOND is the slice
      (numeric) value.
    Any columns beyond the first two are ignored - write the SQL so it
    SELECTs exactly the two columns needed, already aggregated/ordered as
    they should appear on the chart (e.g. `GROUP BY ... ORDER BY ...`); this
    tool only renders what the query returns, it does not aggregate or sort.
    Results are capped at 100 rows for chart readability.
    """
    normalized_type = chart_type.strip().lower()
    if normalized_type not in _VALID_CHART_TYPES:
        return {"error": f"chart_type must be one of {sorted(_VALID_CHART_TYPES)}, got '{chart_type}'"}

    statement_kind = classify_statement(sql)
    if statement_kind not in ("DQL", "OTHER"):
        return {
            "error": f"generate_chart only accepts read (SELECT/WITH) statements; detected "
            f"'{statement_kind}'. Execute/apply the statement first if needed, then chart a "
            "SELECT of the results."
        }

    rows = fetch_all(sql, row_limit=_MAX_CHART_ROWS)
    if not rows:
        return {"error": "Query returned no rows - nothing to chart."}

    columns = list(rows[0].keys())
    if len(columns) < 2:
        return {
            "error": f"Query must return at least 2 columns (label, value); got {len(columns)}. "
            "Adjust the SQL to SELECT the category/period column and the numeric value column."
        }
    label_col, value_col = columns[0], columns[1]
    labels = [str(row[label_col]) for row in rows]
    try:
        values = [float(row[value_col]) for row in rows if row[value_col] is not None]
    except (TypeError, ValueError):
        return {"error": f"Second column '{value_col}' must be numeric to chart - got non-numeric values."}
    if len(values) != len(rows):
        return {"error": f"Second column '{value_col}' contains null values - filter those out before charting."}

    _cleanup_expired()
    file_id = uuid.uuid4().hex
    file_path = CHART_DIR / f"{file_id}.png"

    fig, ax = plt.subplots(figsize=(8, 5), dpi=120)
    if normalized_type == "bar":
        ax.bar(labels, values, color=_CHART_COLOR)
        ax.set_xlabel(x_label or label_col)
        ax.set_ylabel(y_label or value_col)
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right")
    elif normalized_type == "line":
        ax.plot(labels, values, marker="o", color=_CHART_COLOR)
        ax.set_xlabel(x_label or label_col)
        ax.set_ylabel(y_label or value_col)
        plt.setp(ax.get_xticklabels(), rotation=45, ha="right")
    else:  # pie
        ax.pie(values, labels=labels, autopct="%1.1f%%", startangle=90)
        ax.axis("equal")

    ax.set_title(title)
    fig.tight_layout()
    fig.savefig(file_path)
    plt.close(fig)

    return {
        "chart_type": normalized_type,
        "row_count": len(rows),
        "download_url": _build_download_url(file_path.name),
        "expires_in_seconds": settings.CHART_TTL_SECONDS,
    }


async def download_chart(request: Request) -> Response:
    """GET /charts/{file_id} - serve a previously generated chart PNG."""
    file_id = request.path_params["file_id"]
    if not _SAFE_FILE_ID_RE.match(file_id):
        return JSONResponse({"error": "Invalid file id"}, status_code=400)

    file_path = CHART_DIR / file_id
    if not file_path.is_file():
        return JSONResponse({"error": "File not found or expired"}, status_code=404)

    return FileResponse(path=file_path, media_type="image/png", filename=file_path.name)
