"""get_object_ddl: return the CREATE/DDL statement for a table, view,
materialized view, function, procedure, trigger, sequence, or index.

Postgres has no single built-in "SHOW CREATE TABLE"-equivalent for tables, so
table DDL is reconstructed from pg_catalog (columns via format_type/pg_attrdef,
constraints via pg_get_constraintdef, indexes via pg_indexes, triggers via
pg_get_triggerdef). Views/materialized views/functions/procedures/triggers/
indexes each have a direct pg_catalog builtin that returns their full
definition, so those are just wrapped/used as-is.
"""
from db_utils import fetch_all
from mcp_instance import mcp

_VALID_TYPES = {
    "table",
    "view",
    "materialized_view",
    "function",
    "procedure",
    "trigger",
    "sequence",
    "index",
}


def _list_schemas() -> list[str]:
    rows = fetch_all(
        """
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name NOT IN ('pg_catalog', 'information_schema')
          AND schema_name NOT LIKE 'pg_toast%'
          AND schema_name NOT LIKE 'pg_temp%'
        ORDER BY schema_name
        """
    )
    return [row["schema_name"] for row in rows]


def _find_relation(schema: str, name: str) -> dict | None:
    rows = fetch_all(
        """
        SELECT c.oid, c.relkind
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND c.relname = %s
        """,
        (schema, name),
    )
    return rows[0] if rows else None


def _build_table_ddl(schema: str, name: str, oid: int) -> dict:
    columns = fetch_all(
        """
        SELECT
            a.attname AS column_name,
            format_type(a.atttypid, a.atttypmod) AS data_type,
            a.attnotnull AS not_null,
            pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
            a.attidentity AS identity,
            a.attgenerated AS generated
        FROM pg_attribute a
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE a.attrelid = %s AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum
        """,
        (oid,),
    )
    constraints = fetch_all(
        """
        SELECT conname, contype, pg_get_constraintdef(oid, true) AS def
        FROM pg_constraint
        WHERE conrelid = %s AND contype != 'n'
        ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 WHEN 'c' THEN 3 ELSE 4 END, conname
        """,
        (oid,),
    )
    indexes = fetch_all(
        """
        SELECT indexname, indexdef
        FROM pg_indexes
        WHERE schemaname = %s AND tablename = %s
        ORDER BY indexname
        """,
        (schema, name),
    )
    triggers = fetch_all(
        """
        SELECT t.tgname, pg_get_triggerdef(t.oid, true) AS def
        FROM pg_trigger t
        WHERE t.tgrelid = %s AND NOT t.tgisinternal
        ORDER BY t.tgname
        """,
        (oid,),
    )
    comment_rows = fetch_all("SELECT obj_description(%s, 'pg_class') AS comment", (oid,))
    comment = comment_rows[0]["comment"] if comment_rows else None

    column_lines = []
    for col in columns:
        line = f"{col['column_name']} {col['data_type']}"
        if col["identity"] == "a":
            line += " GENERATED ALWAYS AS IDENTITY"
        elif col["identity"] == "d":
            line += " GENERATED BY DEFAULT AS IDENTITY"
        elif col["generated"] == "s" and col["default_expr"]:
            line += f" GENERATED ALWAYS AS ({col['default_expr']}) STORED"
        elif col["default_expr"]:
            line += f" DEFAULT {col['default_expr']}"
        if col["not_null"] and col["identity"] not in ("a", "d"):
            line += " NOT NULL"
        column_lines.append(line)

    constraint_names = {c["conname"] for c in constraints}
    for c in constraints:
        column_lines.append(f"CONSTRAINT {c['conname']} {c['def']}")

    table_stmt = f"CREATE TABLE {schema}.{name} (\n    " + ",\n    ".join(column_lines) + "\n);"

    ddl_parts = [table_stmt]
    for idx in indexes:
        if idx["indexname"] not in constraint_names:
            ddl_parts.append(idx["indexdef"] + ";")
    for trig in triggers:
        ddl_parts.append(trig["def"] + ";")

    return {
        "schema": schema,
        "object_type": "table",
        "name": name,
        "ddl": "\n\n".join(ddl_parts),
        "comment": comment,
    }


def _build_view_ddl(schema: str, name: str, oid: int, materialized: bool) -> dict:
    rows = fetch_all("SELECT pg_get_viewdef(%s, true) AS def", (oid,))
    viewdef = rows[0]["def"].rstrip().rstrip(";") if rows and rows[0]["def"] else ""
    keyword = "MATERIALIZED VIEW" if materialized else "OR REPLACE VIEW"
    ddl = f"CREATE {keyword} {schema}.{name} AS\n{viewdef};"
    comment_rows = fetch_all("SELECT obj_description(%s, 'pg_class') AS comment", (oid,))
    comment = comment_rows[0]["comment"] if comment_rows else None
    return {
        "schema": schema,
        "object_type": "materialized_view" if materialized else "view",
        "name": name,
        "ddl": ddl,
        "comment": comment,
    }


def _build_sequence_ddl(schema: str, name: str) -> dict | None:
    rows = fetch_all(
        """
        SELECT data_type, start_value, min_value, max_value, increment_by, cycle, cache_size
        FROM pg_sequences
        WHERE schemaname = %s AND sequencename = %s
        """,
        (schema, name),
    )
    if not rows:
        return None
    s = rows[0]
    cycle_clause = "CYCLE" if s["cycle"] else "NO CYCLE"
    ddl = (
        f"CREATE SEQUENCE {schema}.{name}\n"
        f"    AS {s['data_type']}\n"
        f"    START WITH {s['start_value']}\n"
        f"    INCREMENT BY {s['increment_by']}\n"
        f"    MINVALUE {s['min_value']}\n"
        f"    MAXVALUE {s['max_value']}\n"
        f"    CACHE {s['cache_size']}\n"
        f"    {cycle_clause};"
    )
    return {"schema": schema, "object_type": "sequence", "name": name, "ddl": ddl}


def _build_index_ddl(schema: str, name: str) -> dict | None:
    rows = fetch_all(
        "SELECT indexdef FROM pg_indexes WHERE schemaname = %s AND indexname = %s",
        (schema, name),
    )
    if not rows:
        return None
    return {"schema": schema, "object_type": "index", "name": name, "ddl": rows[0]["indexdef"] + ";"}


def _find_function_ddls(schema: str, name: str, requested_type: str | None) -> list[dict]:
    if requested_type == "function":
        kind_filter = "AND p.prokind = 'f'"
    elif requested_type == "procedure":
        kind_filter = "AND p.prokind = 'p'"
    else:
        kind_filter = "AND p.prokind IN ('f', 'p')"
    rows = fetch_all(
        f"""
        SELECT p.oid, p.prokind, pg_get_function_identity_arguments(p.oid) AS args
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = %s AND p.proname = %s {kind_filter}
        """,
        (schema, name),
    )
    results = []
    for row in rows:
        ddl_rows = fetch_all("SELECT pg_get_functiondef(%s) AS def", (row["oid"],))
        ddl = ddl_rows[0]["def"] if ddl_rows else None
        results.append(
            {
                "schema": schema,
                "object_type": "procedure" if row["prokind"] == "p" else "function",
                "name": name,
                "signature": f"{name}({row['args']})",
                "ddl": ddl,
            }
        )
    return results


def _find_trigger_ddls(schema: str, name: str) -> list[dict]:
    rows = fetch_all(
        """
        SELECT t.oid, c.relname AS table_name
        FROM pg_trigger t
        JOIN pg_class c ON c.oid = t.tgrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = %s AND t.tgname = %s AND NOT t.tgisinternal
        """,
        (schema, name),
    )
    results = []
    for row in rows:
        ddl_rows = fetch_all("SELECT pg_get_triggerdef(%s, true) AS def", (row["oid"],))
        ddl = (ddl_rows[0]["def"] + ";") if ddl_rows and ddl_rows[0]["def"] else None
        results.append(
            {
                "schema": schema,
                "object_type": "trigger",
                "name": name,
                "table": row["table_name"],
                "ddl": ddl,
            }
        )
    return results


@mcp.tool()
def get_object_ddl(object_name: str, object_type: str | None = None, schema: str | None = None) -> dict:
    """Return the CREATE/DDL statement(s) for a database object - a table, view,
    materialized view, function, procedure, trigger, sequence, or index - so the
    user can see exactly how to recreate it.

    Use this whenever the user asks for the "DDL", "definition", "create query",
    "create statement", or "how is X defined" for a named object, e.g. "give me
    the DDL for table customers", "show me the definition of procedure
    add_two_nums", "create query for the orders_view view".

    Args:
        object_name: The exact name of the table/view/function/procedure/trigger/
            sequence/index (no schema prefix).
        object_type: Optional hint to narrow the search - one of "table", "view",
            "materialized_view", "function", "procedure", "trigger", "sequence",
            "index". Leave unset if you don't know the type; every matching
            object across all types will be returned.
        schema: Optional schema to restrict the search to. Leave unset to search
            every non-system schema in the database.

    Returns a dict with `matches`: a list of objects (there can be more than one
    match - e.g. an overloaded function/procedure with multiple signatures, or
    the same object name existing in more than one schema). Each match has at
    least `schema`, `object_type`, `name`, and `ddl`. Tables also include
    `comment` (business documentation, if any) and their DDL bundles CREATE
    TABLE plus any non-constraint indexes and triggers as one script. Functions/
    procedures include `signature` (name + argument types) since the same name
    can be overloaded. If `match_count` is 0, the object was not found in the
    schemas searched (see `schemas_searched`).
    """
    normalized_type = object_type.strip().lower().replace(" ", "_") if object_type else None
    if normalized_type and normalized_type not in _VALID_TYPES:
        return {
            "error": f"Invalid object_type '{object_type}'. Must be one of: {sorted(_VALID_TYPES)}",
        }

    schemas = [schema] if schema else _list_schemas()
    matches: list[dict] = []

    for sch in schemas:
        if normalized_type in (None, "table", "view", "materialized_view", "sequence", "index"):
            rel = _find_relation(sch, object_name)
            if rel:
                relkind = rel["relkind"]
                oid = rel["oid"]
                if relkind in ("r", "p") and normalized_type in (None, "table"):
                    matches.append(_build_table_ddl(sch, object_name, oid))
                elif relkind == "v" and normalized_type in (None, "view"):
                    matches.append(_build_view_ddl(sch, object_name, oid, materialized=False))
                elif relkind == "m" and normalized_type in (None, "materialized_view"):
                    matches.append(_build_view_ddl(sch, object_name, oid, materialized=True))
                elif relkind == "S" and normalized_type in (None, "sequence"):
                    seq = _build_sequence_ddl(sch, object_name)
                    if seq:
                        matches.append(seq)
                elif relkind in ("i", "I") and normalized_type in (None, "index"):
                    idx = _build_index_ddl(sch, object_name)
                    if idx:
                        matches.append(idx)

        if normalized_type in (None, "function", "procedure"):
            matches.extend(_find_function_ddls(sch, object_name, normalized_type))

        if normalized_type in (None, "trigger"):
            matches.extend(_find_trigger_ddls(sch, object_name))

    return {
        "object_name": object_name,
        "requested_type": normalized_type,
        "schemas_searched": schemas,
        "match_count": len(matches),
        "matches": matches,
    }
