"""ER diagram tool: renders an Entity-Relationship diagram as a PNG for a
schema (or a specific subset of tables within it), showing each table's
columns (primary/foreign keys marked) and the foreign-key relationships
between the included tables.

Saved as a downloadable image, mirroring tools/export_tools.py's pattern: its
own directory, its own opportunistic TTL cleanup, and its own plain
(unauthenticated) Starlette download route mounted in server.py at
GET /diagrams/{file_id}.
"""
import math
import re
import time
import uuid
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from starlette.requests import Request
from starlette.responses import FileResponse, JSONResponse, Response

from config import settings
from db_utils import fetch_all
from mcp_instance import mcp

DIAGRAM_DIR = Path(settings.DIAGRAM_DIR)
DIAGRAM_DIR.mkdir(parents=True, exist_ok=True)

# Only ever generated by uuid.uuid4().hex, so this is just a defensive check
# against path traversal / unexpected characters before touching the filesystem.
_SAFE_FILE_ID_RE = re.compile(r"^[a-f0-9]{32}\.png$")

# Layout constants for the rendered diagram.
_BOX_MIN_WIDTH = 220
_BOX_MAX_WIDTH = 380
_HEADER_HEIGHT = 32
_ROW_HEIGHT = 20
_PADDING = 10
_MAX_COLUMNS_SHOWN = 25
_MARGIN_X = 70
_MARGIN_Y = 90
_OUTER_MARGIN = 40

_HEADER_COLOR = (25, 85, 160)
_HEADER_TEXT_COLOR = (255, 255, 255)
_BOX_BORDER_COLOR = (60, 60, 60)
_BOX_FILL_COLOR = (250, 250, 250)
_PK_TEXT_COLOR = (150, 40, 0)
_FK_TEXT_COLOR = (0, 90, 140)
_COLUMN_TEXT_COLOR = (30, 30, 30)
_ARROW_COLOR = (90, 90, 90)
_LABEL_TEXT_COLOR = (70, 70, 70)


def _cleanup_expired() -> None:
    """Delete diagram files older than DIAGRAM_TTL_SECONDS. Best-effort, called
    opportunistically before writing a new diagram (no background task/thread)."""
    cutoff = time.time() - settings.DIAGRAM_TTL_SECONDS
    for path in DIAGRAM_DIR.glob("*"):
        try:
            if path.is_file() and path.stat().st_mtime < cutoff:
                path.unlink()
        except OSError:
            pass


def _build_download_url(file_name: str) -> str:
    base = settings.EXPORT_PUBLIC_BASE_URL.rstrip("/")
    return f"{base}/diagrams/{file_name}"


def _load_font(size: int):
    try:
        return ImageFont.load_default(size=size)
    except TypeError:
        # Older Pillow versions don't accept a `size` kwarg here.
        return ImageFont.load_default()


def _text_width(draw: ImageDraw.ImageDraw, text: str, font) -> int:
    bbox = draw.textbbox((0, 0), text, font=font)
    return bbox[2] - bbox[0]


def _resolve_tables(schema: str, tables: list[str] | None) -> list[str]:
    if tables:
        seen: set[str] = set()
        ordered = []
        for t in tables:
            if t not in seen:
                seen.add(t)
                ordered.append(t)
        return ordered

    rows = fetch_all(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = %s AND table_type = 'BASE TABLE'
        ORDER BY table_name
        """,
        (schema,),
    )
    return [r["table_name"] for r in rows]


def _fetch_columns(schema: str, table_names: list[str]) -> dict[str, list[dict]]:
    rows = fetch_all(
        """
        SELECT table_name, column_name, data_type
        FROM information_schema.columns
        WHERE table_schema = %s AND table_name = ANY(%s)
        ORDER BY table_name, ordinal_position
        """,
        (schema, table_names),
    )
    columns_by_table: dict[str, list[dict]] = {t: [] for t in table_names}
    for row in rows:
        columns_by_table.setdefault(row["table_name"], []).append(row)
    return columns_by_table


def _fetch_primary_keys(schema: str, table_names: list[str]) -> set[tuple[str, str]]:
    rows = fetch_all(
        """
        SELECT tc.table_name, kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
        WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = %s AND tc.table_name = ANY(%s)
        """,
        (schema, table_names),
    )
    return {(r["table_name"], r["column_name"]) for r in rows}


def _fetch_foreign_keys(schema: str, table_names: list[str]) -> list[dict]:
    rows = fetch_all(
        """
        SELECT
            tc.table_name AS table_name,
            kcu.column_name AS column_name,
            ccu.table_name AS foreign_table_name,
            ccu.column_name AS foreign_column_name,
            tc.constraint_name AS constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage ccu
          ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = %s AND tc.table_name = ANY(%s)
        ORDER BY tc.table_name, kcu.column_name
        """,
        (schema, table_names),
    )
    # Only draw relationships where BOTH ends are in the diagram - a FK
    # pointing at a table that wasn't included has no box to draw an arrow to.
    table_set = set(table_names)
    return [r for r in rows if r["foreign_table_name"] in table_set]


def _edge_point(box: tuple[float, float, float, float], other_center: tuple[float, float]) -> tuple[float, float]:
    """Point where the line from `box`'s center to `other_center` crosses `box`'s boundary."""
    left, top, right, bottom = box
    cx, cy = (left + right) / 2, (top + bottom) / 2
    ox, oy = other_center
    dx, dy = ox - cx, oy - cy
    if dx == 0 and dy == 0:
        return cx, cy
    candidates = []
    if dx != 0:
        t = (right - cx) / dx if dx > 0 else (left - cx) / dx
        y_at = cy + t * dy
        if top <= y_at <= bottom and t > 0:
            candidates.append((t, (cx + t * dx, y_at)))
    if dy != 0:
        t = (bottom - cy) / dy if dy > 0 else (top - cy) / dy
        x_at = cx + t * dx
        if left <= x_at <= right and t > 0:
            candidates.append((t, (x_at, cy + t * dy)))
    if not candidates:
        return cx, cy
    candidates.sort(key=lambda c: c[0])
    return candidates[0][1]


def _draw_arrowhead(draw: ImageDraw.ImageDraw, tip: tuple[float, float], direction: tuple[float, float], color, size: float = 8) -> None:
    angle = math.atan2(direction[1], direction[0])
    left_angle = angle + math.radians(150)
    right_angle = angle - math.radians(150)
    p1 = (tip[0] + size * math.cos(left_angle), tip[1] + size * math.sin(left_angle))
    p2 = (tip[0] + size * math.cos(right_angle), tip[1] + size * math.sin(right_angle))
    draw.polygon([tip, p1, p2], fill=color)


def _render_diagram(
    table_names: list[str],
    columns_by_table: dict[str, list[dict]],
    primary_keys: set[tuple[str, str]],
    foreign_keys: list[dict],
) -> Image.Image:
    header_font = _load_font(14)
    column_font = _load_font(12)
    label_font = _load_font(11)

    measure_img = Image.new("RGB", (1, 1))
    measure_draw = ImageDraw.Draw(measure_img)

    box_sizes: dict[str, tuple[int, int, list[str]]] = {}
    for name in table_names:
        cols = columns_by_table.get(name, [])
        shown = cols[:_MAX_COLUMNS_SHOWN]
        extra = len(cols) - len(shown)
        lines = []
        for col in shown:
            tags = []
            if (name, col["column_name"]) in primary_keys:
                tags.append("PK")
            if any(fk["table_name"] == name and fk["column_name"] == col["column_name"] for fk in foreign_keys):
                tags.append("FK")
            tag_str = f" [{'/'.join(tags)}]" if tags else ""
            lines.append(f"{col['column_name']}: {col['data_type']}{tag_str}")
        if extra > 0:
            lines.append(f"... {extra} more column(s)")

        max_line_width = _text_width(measure_draw, name, header_font)
        for line in lines:
            max_line_width = max(max_line_width, _text_width(measure_draw, line, column_font))
        width = max(_BOX_MIN_WIDTH, min(_BOX_MAX_WIDTH, max_line_width + _PADDING * 2))
        height = _HEADER_HEIGHT + _PADDING * 2 + len(lines) * _ROW_HEIGHT
        box_sizes[name] = (width, height, lines)

    n = len(table_names)
    cols_count = max(1, math.ceil(math.sqrt(n)))
    rows_count = math.ceil(n / cols_count)

    col_widths = [0] * cols_count
    row_heights = [0] * rows_count
    for idx, name in enumerate(table_names):
        r, c = divmod(idx, cols_count)
        w, h, _ = box_sizes[name]
        col_widths[c] = max(col_widths[c], w)
        row_heights[r] = max(row_heights[r], h)

    col_x = [_OUTER_MARGIN]
    for w in col_widths:
        col_x.append(col_x[-1] + w + _MARGIN_X)
    row_y = [_OUTER_MARGIN]
    for h in row_heights:
        row_y.append(row_y[-1] + h + _MARGIN_Y)

    canvas_width = col_x[-1] - _MARGIN_X + _OUTER_MARGIN
    canvas_height = row_y[-1] - _MARGIN_Y + _OUTER_MARGIN

    img = Image.new("RGB", (int(canvas_width), int(canvas_height)), "white")
    draw = ImageDraw.Draw(img)

    boxes: dict[str, tuple[float, float, float, float]] = {}
    for idx, name in enumerate(table_names):
        r, c = divmod(idx, cols_count)
        w, h, lines = box_sizes[name]
        x0, y0 = col_x[c], row_y[r]
        x1, y1 = x0 + w, y0 + h
        boxes[name] = (x0, y0, x1, y1)

        draw.rectangle([x0, y0, x1, y1], fill=_BOX_FILL_COLOR, outline=_BOX_BORDER_COLOR, width=2)
        draw.rectangle([x0, y0, x1, y0 + _HEADER_HEIGHT], fill=_HEADER_COLOR)
        draw.text((x0 + _PADDING, y0 + (_HEADER_HEIGHT - 14) / 2), name, fill=_HEADER_TEXT_COLOR, font=header_font)

        ty = y0 + _HEADER_HEIGHT + _PADDING
        for line in lines:
            color = _COLUMN_TEXT_COLOR
            if "[PK" in line:
                color = _PK_TEXT_COLOR
            elif "FK]" in line or "/FK]" in line:
                color = _FK_TEXT_COLOR
            draw.text((x0 + _PADDING, ty), line, fill=color, font=column_font)
            ty += _ROW_HEIGHT

    for fk in foreign_keys:
        src_box = boxes.get(fk["table_name"])
        dst_box = boxes.get(fk["foreign_table_name"])
        if not src_box or not dst_box or src_box == dst_box:
            continue  # missing box, or a self-referencing FK (no line to draw)

        src_center = ((src_box[0] + src_box[2]) / 2, (src_box[1] + src_box[3]) / 2)
        dst_center = ((dst_box[0] + dst_box[2]) / 2, (dst_box[1] + dst_box[3]) / 2)
        start = _edge_point(src_box, dst_center)
        end = _edge_point(dst_box, src_center)
        draw.line([start, end], fill=_ARROW_COLOR, width=2)
        _draw_arrowhead(draw, end, (end[0] - start[0], end[1] - start[1]), _ARROW_COLOR)

        label = f"{fk['column_name']} -> {fk['foreign_column_name']}"
        mid = ((start[0] + end[0]) / 2, (start[1] + end[1]) / 2)
        label_w = _text_width(draw, label, label_font)
        draw.rectangle(
            [mid[0] - label_w / 2 - 3, mid[1] - 8, mid[0] + label_w / 2 + 3, mid[1] + 8],
            fill=(255, 255, 255),
            outline=(200, 200, 200),
        )
        draw.text((mid[0] - label_w / 2, mid[1] - 7), label, fill=_LABEL_TEXT_COLOR, font=label_font)

    return img


@mcp.tool()
def generate_er_diagram(schema: str = "public", tables: list[str] | None = None) -> dict:
    """Generate an Entity-Relationship (ER) diagram as a downloadable PNG image
    for a schema, or for a specific subset of tables within it.

    - Omit `tables` to diagram every table in `schema` (e.g. "show me the ER
      diagram of the configuration schema").
    - Pass `tables` to diagram only those tables and the foreign-key
      relationships directly between them (e.g. "give me the ER diagram for
      t1, t2, t3, t4, t5 only" -> tables=["t1", "t2", "t3", "t4", "t5"]).

    Each table is drawn as a box listing its columns (primary keys marked
    [PK], foreign keys marked [FK]); arrows show foreign-key relationships
    between the included tables (self-references and FKs pointing to a table
    outside the given set are omitted from the drawing).

    Returns `download_url` (valid for `expires_in_seconds`) which can be shown
    inline as a markdown image and/or downloaded as a .png file.
    """
    table_names = _resolve_tables(schema, tables)
    if not table_names:
        scope = f" matching {tables}" if tables else ""
        return {"error": f"No tables found for schema '{schema}'{scope}"}

    columns_by_table = _fetch_columns(schema, table_names)
    missing = [t for t in table_names if not columns_by_table.get(t)]
    table_names = [t for t in table_names if columns_by_table.get(t)]
    if not table_names:
        return {"error": f"None of the requested tables were found in schema '{schema}': {missing}"}

    primary_keys = _fetch_primary_keys(schema, table_names)
    foreign_keys = _fetch_foreign_keys(schema, table_names)

    _cleanup_expired()
    image = _render_diagram(table_names, columns_by_table, primary_keys, foreign_keys)
    file_id = f"{uuid.uuid4().hex}.png"
    file_path = DIAGRAM_DIR / file_id
    image.save(file_path, format="PNG")

    result = {
        "schema": schema,
        "tables": table_names,
        "table_count": len(table_names),
        "relationship_count": len(foreign_keys),
        "download_url": _build_download_url(file_id),
        "expires_in_seconds": settings.DIAGRAM_TTL_SECONDS,
    }
    if missing:
        result["tables_not_found"] = missing
    return result


async def download_diagram(request: Request) -> Response:
    """GET /diagrams/{file_id} - serve a previously generated ER diagram PNG."""
    file_id = request.path_params["file_id"]
    if not _SAFE_FILE_ID_RE.match(file_id):
        return JSONResponse({"error": "Invalid file id"}, status_code=400)

    file_path = DIAGRAM_DIR / file_id
    if not file_path.is_file():
        return JSONResponse({"error": "File not found or expired"}, status_code=404)

    return FileResponse(path=file_path, media_type="image/png", filename=file_path.name)
