"""Export tools: run a DQL query and save its full result set to disk as a
CSV or JSON file, returning an HTTP download link.

The download link is served by a plain (unauthenticated) Starlette route
mounted in server.py at GET /exports/{file_id} - see download_export() below.
Files are named with a random UUID (no user input in the path) and expire
after EXPORT_TTL_SECONDS; expired files are opportunistically swept on every
export call (see _cleanup_expired).
"""
import csv
import json
import re
import time
import uuid
from pathlib import Path

from starlette.requests import Request
from starlette.responses import FileResponse, JSONResponse, Response

from config import settings
from db_utils import fetch_all
from mcp_instance import mcp
from security import classify_statement

EXPORT_DIR = Path(settings.EXPORT_DIR)
EXPORT_DIR.mkdir(parents=True, exist_ok=True)

# Only ever generated by uuid.uuid4().hex, so this is just a defensive check
# against path traversal / unexpected characters before touching the filesystem.
_SAFE_FILE_ID_RE = re.compile(r"^[a-f0-9]{32}\.(csv|json)$")


def _cleanup_expired() -> None:
    """Delete export files older than EXPORT_TTL_SECONDS. Best-effort, called
    opportunistically before writing a new export (no background task/thread)."""
    cutoff = time.time() - settings.EXPORT_TTL_SECONDS
    for path in EXPORT_DIR.glob("*"):
        try:
            if path.is_file() and path.stat().st_mtime < cutoff:
                path.unlink()
        except OSError:
            pass


def _validate_dql(sql: str) -> str | None:
    kind = classify_statement(sql)
    if kind not in ("DQL", "OTHER"):
        return (
            f"Export tools only accept read (SELECT/WITH) statements; detected '{kind}'. "
            "Use execute_ddl_dml for writes instead."
        )
    return None


def _build_download_url(file_name: str) -> str:
    base = settings.EXPORT_PUBLIC_BASE_URL.rstrip("/")
    return f"{base}/exports/{file_name}"


def _write_csv(rows: list[dict], file_id: str) -> Path:
    file_path = EXPORT_DIR / f"{file_id}.csv"
    with file_path.open("w", newline="", encoding="utf-8") as f:
        if rows:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
    return file_path


def _write_json(rows: list[dict], file_id: str) -> Path:
    file_path = EXPORT_DIR / f"{file_id}.json"
    file_path.write_text(json.dumps(rows, indent=2, default=str), encoding="utf-8")
    return file_path


@mcp.tool()
def export_query_to_csv(sql: str) -> dict:
    """Execute a read-only (DQL) SQL statement and save its full result set as a
    downloadable CSV file. Returns a `download_url` that stays valid for
    `expires_in_seconds` (see EXPORT_TTL_SECONDS), plus the exported row_count.

    Row count is capped at MAX_EXPORT_ROWS (much higher than the normal
    execute_query preview cap) so very large result sets are still bounded.
    """
    error = _validate_dql(sql)
    if error:
        return {"error": error}

    _cleanup_expired()
    rows = fetch_all(sql, row_limit=settings.MAX_EXPORT_ROWS)
    file_path = _write_csv(rows, uuid.uuid4().hex)

    return {
        "row_count": len(rows),
        "format": "csv",
        "download_url": _build_download_url(file_path.name),
        "expires_in_seconds": settings.EXPORT_TTL_SECONDS,
    }


@mcp.tool()
def export_query_to_json(sql: str) -> dict:
    """Execute a read-only (DQL) SQL statement and save its full result set as a
    downloadable JSON file. Returns a `download_url` that stays valid for
    `expires_in_seconds` (see EXPORT_TTL_SECONDS), plus the exported row_count.

    Row count is capped at MAX_EXPORT_ROWS (much higher than the normal
    execute_query preview cap) so very large result sets are still bounded.
    """
    error = _validate_dql(sql)
    if error:
        return {"error": error}

    _cleanup_expired()
    rows = fetch_all(sql, row_limit=settings.MAX_EXPORT_ROWS)
    file_path = _write_json(rows, uuid.uuid4().hex)

    return {
        "row_count": len(rows),
        "format": "json",
        "download_url": _build_download_url(file_path.name),
        "expires_in_seconds": settings.EXPORT_TTL_SECONDS,
    }


async def download_export(request: Request) -> Response:
    """GET /exports/{file_id} - serve a previously exported CSV/JSON file."""
    file_id = request.path_params["file_id"]
    if not _SAFE_FILE_ID_RE.match(file_id):
        return JSONResponse({"error": "Invalid file id"}, status_code=400)

    file_path = EXPORT_DIR / file_id
    if not file_path.is_file():
        return JSONResponse({"error": "File not found or expired"}, status_code=404)

    media_type = "text/csv" if file_path.suffix == ".csv" else "application/json"
    return FileResponse(path=file_path, media_type=media_type, filename=file_path.name)
