"""generate_sql_script: bundle one or more SQL statements (DDL/DML/DQL) that the
model has already generated into a single downloadable `.sql` file - e.g. a full
"create an e-commerce schema" script with tables, foreign keys, views,
sequences, functions, procedures, triggers, and indexes all in one file.

This tool does NOT execute anything against the database - it only assembles
and persists SQL text. Mirrors the tools/export_tools.py and
tools/er_diagram_tools.py pattern: its own directory, its own opportunistic TTL
cleanup, and its own plain (unauthenticated) Starlette download route mounted
in server.py at GET /sql-scripts/{file_id}.
"""
import re
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

from starlette.requests import Request
from starlette.responses import FileResponse, JSONResponse, Response

from config import settings
from mcp_instance import mcp
from security import classify_statement

SQL_SCRIPT_DIR = Path(settings.SQL_SCRIPT_DIR)
SQL_SCRIPT_DIR.mkdir(parents=True, exist_ok=True)

# Only ever generated by uuid.uuid4().hex, so this is just a defensive check
# against path traversal / unexpected characters before touching the filesystem.
_SAFE_FILE_ID_RE = re.compile(r"^[a-f0-9]{32}\.sql$")

# Only used to build a user-friendly download filename; the file on disk is
# always named by uuid (see _SAFE_FILE_ID_RE) regardless of this value.
_UNSAFE_NAME_CHARS_RE = re.compile(r"[^A-Za-z0-9_.-]+")
_DEFAULT_FILENAME = "generated_script.sql"


def _cleanup_expired() -> None:
    """Delete script files older than SQL_SCRIPT_TTL_SECONDS. Best-effort, called
    opportunistically before writing a new script (no background task/thread)."""
    cutoff = time.time() - settings.SQL_SCRIPT_TTL_SECONDS
    for path in SQL_SCRIPT_DIR.glob("*"):
        try:
            if path.is_file() and path.stat().st_mtime < cutoff:
                path.unlink()
        except OSError:
            pass


def _sanitize_download_name(filename: str | None) -> str:
    if not filename or not filename.strip():
        return _DEFAULT_FILENAME
    # Path(...).name drops any directory components a caller might include.
    name = _UNSAFE_NAME_CHARS_RE.sub("_", Path(filename.strip()).name)
    if not name or name in (".", ".."):
        return _DEFAULT_FILENAME
    if not name.lower().endswith(".sql"):
        name += ".sql"
    return name


def _build_download_url(file_id: str, download_name: str) -> str:
    base = settings.EXPORT_PUBLIC_BASE_URL.rstrip("/")
    return f"{base}/sql-scripts/{file_id}?name={quote(download_name)}"


def _build_script_text(statements: list[str], title: str | None, counts: dict[str, int]) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    summary = ", ".join(f"{count} {kind}" for kind, count in counts.items() if count) or "0 statements"
    header = (
        f"-- {title.strip()}\n" if title and title.strip() else "-- Generated SQL script\n"
    ) + f"-- Generated by PG AI Assistant on {generated_at}\n" f"-- Contains: {summary}\n\n"

    body_parts = []
    for stmt in statements:
        text = stmt.strip()
        if not text:
            continue
        if not text.endswith(";"):
            text += ";"
        body_parts.append(text)
    return header + "\n\n".join(body_parts) + "\n"


@mcp.tool()
def generate_sql_script(statements: list[str], filename: str | None = None, title: str | None = None) -> dict:
    """Bundle one or more SQL statements into a single downloadable `.sql` file.

    Use this whenever the user wants a `.sql` file containing a combination of
    multiple DDL/DML/DQL statements generated all at once - e.g. "create an
    e-commerce schema with all required tables, foreign keys, views, sequences,
    procedures, functions, triggers, and indexes, then give me the .sql file",
    or "generate a script that creates these 5 tables plus their indexes".

    This tool does NOT execute anything against the database - it only writes
    the SQL text you provide to a file and returns a download link. You are
    responsible for generating valid, PostgreSQL-compatible SQL yourself
    (following the same standards you'd use for execute_ddl_dml/execute_query,
    including verifying referenced tables/columns with list_tables/describe_table
    first) before calling this tool. If the user also wants the schema actually
    applied to the connected database (not just a file), call execute_ddl_dml
    for each statement separately in addition to calling this tool - this tool
    alone never changes the database.

    Args:
        statements: The SQL statements to include, in the exact order they
            should appear in the file. Order matters - e.g. a CREATE TABLE
            referenced by a FOREIGN KEY must come before the table that
            references it; CREATE TABLE before CREATE INDEX/CREATE TRIGGER on
            it; tables/views before a CREATE FUNCTION that queries them - so
            the file can run top-to-bottom without errors. Each entry should be
            exactly one statement; a trailing `;` is added automatically if
            missing.
        filename: Optional file name for the download (e.g. "ecommerce_schema.sql").
            A `.sql` extension is added automatically if missing. Defaults to
            "generated_script.sql" if omitted.
        title: Optional short description written as a comment at the top of the
            file (e.g. "E-commerce schema: tables, views, sequences, triggers").

    Returns `download_url` (valid for `expires_in_seconds`), `statement_count`,
    and `statement_breakdown` (count per DDL/DML/DQL/OTHER kind).
    """
    non_empty = [s for s in statements if s and s.strip()]
    if not non_empty:
        return {"error": "No non-empty SQL statements were provided."}
    if len(non_empty) > settings.SQL_SCRIPT_MAX_STATEMENTS:
        return {
            "error": f"Too many statements ({len(non_empty)}); "
            f"the limit is {settings.SQL_SCRIPT_MAX_STATEMENTS} per file."
        }

    counts: dict[str, int] = {"DDL": 0, "DML": 0, "DQL": 0, "OTHER": 0}
    for stmt in non_empty:
        counts[classify_statement(stmt)] += 1

    script_text = _build_script_text(non_empty, title, counts)

    _cleanup_expired()
    file_id = f"{uuid.uuid4().hex}.sql"
    (SQL_SCRIPT_DIR / file_id).write_text(script_text, encoding="utf-8")
    download_name = _sanitize_download_name(filename)

    return {
        "download_url": _build_download_url(file_id, download_name),
        "download_filename": download_name,
        "expires_in_seconds": settings.SQL_SCRIPT_TTL_SECONDS,
        "statement_count": len(non_empty),
        "statement_breakdown": {k: v for k, v in counts.items() if v},
    }


async def download_sql_script(request: Request) -> Response:
    """GET /sql-scripts/{file_id}?name=... - serve a previously generated .sql file."""
    file_id = request.path_params["file_id"]
    if not _SAFE_FILE_ID_RE.match(file_id):
        return JSONResponse({"error": "Invalid file id"}, status_code=400)

    file_path = SQL_SCRIPT_DIR / file_id
    if not file_path.is_file():
        return JSONResponse({"error": "File not found or expired"}, status_code=404)

    download_name = _sanitize_download_name(request.query_params.get("name"))
    return FileResponse(path=file_path, media_type="application/sql", filename=download_name)
