-- Ecommerce Schema: schema, sequences, tables, indexes, triggers, functions, and views
-- Generated by PG AI Assistant on 2026-07-17 17:54:38 UTC
-- Contains: 47 DDL, 4 OTHER

CREATE SCHEMA IF NOT EXISTS ecommerce;

CREATE SEQUENCE ecommerce.users_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.addresses_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.categories_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.products_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.product_images_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.carts_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.cart_items_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.orders_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.order_items_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.payments_id_seq START 1 INCREMENT 1;

CREATE SEQUENCE ecommerce.reviews_id_seq START 1 INCREMENT 1;

CREATE TABLE ecommerce.users (
    id BIGINT DEFAULT nextval('ecommerce.users_id_seq') PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.addresses (
    id BIGINT DEFAULT nextval('ecommerce.addresses_id_seq') PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES ecommerce.users(id) ON DELETE CASCADE,
    label VARCHAR(50),
    street_line1 VARCHAR(255) NOT NULL,
    street_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100),
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.categories (
    id BIGINT DEFAULT nextval('ecommerce.categories_id_seq') PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    slug VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    parent_id BIGINT REFERENCES ecommerce.categories(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.products (
    id BIGINT DEFAULT nextval('ecommerce.products_id_seq') PRIMARY KEY,
    category_id BIGINT REFERENCES ecommerce.categories(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    stock_quantity INT NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    sku VARCHAR(100) UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.product_images (
    id BIGINT DEFAULT nextval('ecommerce.product_images_id_seq') PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES ecommerce.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text VARCHAR(255),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.carts (
    id BIGINT DEFAULT nextval('ecommerce.carts_id_seq') PRIMARY KEY,
    user_id BIGINT REFERENCES ecommerce.users(id) ON DELETE CASCADE,
    session_id VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_cart_owner CHECK (user_id IS NOT NULL OR session_id IS NOT NULL)
);

CREATE TABLE ecommerce.cart_items (
    id BIGINT DEFAULT nextval('ecommerce.cart_items_id_seq') PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES ecommerce.carts(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES ecommerce.products(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cart_product UNIQUE (cart_id, product_id)
);

CREATE TABLE ecommerce.orders (
    id BIGINT DEFAULT nextval('ecommerce.orders_id_seq') PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES ecommerce.users(id) ON DELETE RESTRICT,
    shipping_address_id BIGINT REFERENCES ecommerce.addresses(id) ON DELETE SET NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded')),
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    shipping_cost NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (shipping_cost >= 0),
    tax NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (tax >= 0),
    total NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.order_items (
    id BIGINT DEFAULT nextval('ecommerce.order_items_id_seq') PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES ecommerce.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES ecommerce.products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    quantity INT NOT NULL CHECK (quantity > 0),
    line_total NUMERIC(12, 2) GENERATED ALWAYS AS (unit_price * quantity) STORED
);

CREATE TABLE ecommerce.payments (
    id BIGINT DEFAULT nextval('ecommerce.payments_id_seq') PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES ecommerce.orders(id) ON DELETE RESTRICT,
    method VARCHAR(50) NOT NULL CHECK (method IN ('credit_card','debit_card','paypal','bank_transfer','crypto','gift_card')),
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','completed','failed','refunded')),
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    transaction_id VARCHAR(255) UNIQUE,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.reviews (
    id BIGINT DEFAULT nextval('ecommerce.reviews_id_seq') PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES ecommerce.products(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES ecommerce.users(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title VARCHAR(255),
    body TEXT,
    is_verified_purchase BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_product_review UNIQUE (user_id, product_id)
);

CREATE INDEX idx_addresses_user_id ON ecommerce.addresses(user_id);

CREATE INDEX idx_products_category_id ON ecommerce.products(category_id);

CREATE INDEX idx_products_is_active ON ecommerce.products(is_active);

CREATE INDEX idx_products_price ON ecommerce.products(price);

CREATE INDEX idx_product_images_product_id ON ecommerce.product_images(product_id);

CREATE INDEX idx_carts_user_id ON ecommerce.carts(user_id);

CREATE INDEX idx_carts_session_id ON ecommerce.carts(session_id);

CREATE INDEX idx_cart_items_cart_id ON ecommerce.cart_items(cart_id);

CREATE INDEX idx_orders_user_id ON ecommerce.orders(user_id);

CREATE INDEX idx_orders_status ON ecommerce.orders(status);

CREATE INDEX idx_orders_created_at ON ecommerce.orders(created_at);

CREATE INDEX idx_order_items_order_id ON ecommerce.order_items(order_id);

CREATE INDEX idx_payments_order_id ON ecommerce.payments(order_id);

CREATE INDEX idx_payments_status ON ecommerce.payments(status);

CREATE INDEX idx_reviews_product_id ON ecommerce.reviews(product_id);

CREATE INDEX idx_reviews_user_id ON ecommerce.reviews(user_id);

CREATE OR REPLACE FUNCTION ecommerce.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON ecommerce.users
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_addresses_updated_at
    BEFORE UPDATE ON ecommerce.addresses
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_categories_updated_at
    BEFORE UPDATE ON ecommerce.categories
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON ecommerce.products
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_carts_updated_at
    BEFORE UPDATE ON ecommerce.carts
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON ecommerce.orders
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_payments_updated_at
    BEFORE UPDATE ON ecommerce.payments
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_reviews_updated_at
    BEFORE UPDATE ON ecommerce.reviews
    FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE OR REPLACE VIEW ecommerce.v_product_summary AS
SELECT
    p.id,
    p.name,
    p.slug,
    p.price,
    p.stock_quantity,
    p.sku,
    p.is_active,
    c.name AS category_name,
    ROUND(AVG(r.rating), 2) AS avg_rating,
    COUNT(r.id) AS review_count
FROM ecommerce.products p
LEFT JOIN ecommerce.categories c ON c.id = p.category_id
LEFT JOIN ecommerce.reviews r ON r.product_id = p.id
GROUP BY p.id, c.name;

CREATE OR REPLACE VIEW ecommerce.v_order_summary AS
SELECT
    o.id AS order_id,
    o.status,
    o.created_at,
    o.total,
    u.id AS user_id,
    u.email,
    u.first_name,
    u.last_name,
    COUNT(oi.id) AS item_count,
    p.status AS payment_status,
    p.method AS payment_method
FROM ecommerce.orders o
JOIN ecommerce.users u ON u.id = o.user_id
LEFT JOIN ecommerce.order_items oi ON oi.order_id = o.id
LEFT JOIN ecommerce.payments p ON p.order_id = o.id
GROUP BY o.id, u.id, p.status, p.method;

CREATE OR REPLACE VIEW ecommerce.v_cart_details AS
SELECT
    c.id AS cart_id,
    c.user_id,
    c.session_id,
    ci.id AS cart_item_id,
    pr.id AS product_id,
    pr.name AS product_name,
    pr.price AS unit_price,
    ci.quantity,
    (pr.price * ci.quantity) AS line_total
FROM ecommerce.carts c
JOIN ecommerce.cart_items ci ON ci.cart_id = c.id
JOIN ecommerce.products pr ON pr.id = ci.product_id;
