-- Ecommerce Schema: tables, indexes, triggers, functions, and views
-- Generated by PG AI Assistant on 2026-07-17 17:57:51 UTC
-- Contains: 43 DDL, 4 OTHER

CREATE SCHEMA IF NOT EXISTS ecommerce;

CREATE TABLE ecommerce.users (
  user_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email       VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  first_name  VARCHAR(100),
  last_name   VARCHAR(100),
  phone       VARCHAR(30),
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.addresses (
  address_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES ecommerce.users(user_id) ON DELETE CASCADE,
  label        VARCHAR(50) DEFAULT 'home',
  full_name    VARCHAR(200),
  line1        VARCHAR(255) NOT NULL,
  line2        VARCHAR(255),
  city         VARCHAR(100) NOT NULL,
  state        VARCHAR(100),
  postal_code  VARCHAR(20) NOT NULL,
  country      VARCHAR(100) NOT NULL DEFAULT 'US',
  is_default   BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.categories (
  category_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  parent_id     BIGINT REFERENCES ecommerce.categories(category_id) ON DELETE SET NULL,
  name          VARCHAR(150) NOT NULL,
  slug          VARCHAR(150) NOT NULL UNIQUE,
  description   TEXT,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.products (
  product_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category_id   BIGINT REFERENCES ecommerce.categories(category_id) ON DELETE SET NULL,
  name          VARCHAR(255) NOT NULL,
  slug          VARCHAR(255) NOT NULL UNIQUE,
  description   TEXT,
  sku           VARCHAR(100) UNIQUE,
  price         NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  stock_qty     INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.product_images (
  image_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id   BIGINT NOT NULL REFERENCES ecommerce.products(product_id) ON DELETE CASCADE,
  url          TEXT NOT NULL,
  alt_text     VARCHAR(255),
  is_primary   BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order   INT NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.carts (
  cart_id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id      BIGINT REFERENCES ecommerce.users(user_id) ON DELETE CASCADE,
  session_id   VARCHAR(255),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_cart_owner CHECK (user_id IS NOT NULL OR session_id IS NOT NULL)
);

CREATE TABLE ecommerce.cart_items (
  cart_item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  cart_id      BIGINT NOT NULL REFERENCES ecommerce.carts(cart_id) ON DELETE CASCADE,
  product_id   BIGINT NOT NULL REFERENCES ecommerce.products(product_id) ON DELETE CASCADE,
  quantity     INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  added_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (cart_id, product_id)
);

CREATE TABLE ecommerce.orders (
  order_id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL REFERENCES ecommerce.users(user_id) ON DELETE RESTRICT,
  shipping_address_id BIGINT REFERENCES ecommerce.addresses(address_id) ON DELETE SET NULL,
  status           VARCHAR(50) NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending','confirmed','processing','shipped','delivered','cancelled','refunded')),
  subtotal         NUMERIC(12,2) NOT NULL DEFAULT 0,
  shipping_cost    NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax              NUMERIC(12,2) NOT NULL DEFAULT 0,
  total            NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.order_items (
  order_item_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id       BIGINT NOT NULL REFERENCES ecommerce.orders(order_id) ON DELETE CASCADE,
  product_id     BIGINT REFERENCES ecommerce.products(product_id) ON DELETE SET NULL,
  product_name   VARCHAR(255) NOT NULL,
  unit_price     NUMERIC(12,2) NOT NULL,
  quantity       INT NOT NULL CHECK (quantity > 0),
  line_total     NUMERIC(12,2) GENERATED ALWAYS AS (unit_price * quantity) STORED
);

CREATE TABLE ecommerce.payments (
  payment_id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES ecommerce.orders(order_id) ON DELETE RESTRICT,
  method          VARCHAR(50) NOT NULL CHECK (method IN ('credit_card','debit_card','paypal','stripe','bank_transfer','wallet')),
  status          VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','completed','failed','refunded')),
  amount          NUMERIC(12,2) NOT NULL,
  transaction_id  VARCHAR(255) UNIQUE,
  paid_at         TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ecommerce.reviews (
  review_id    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  product_id   BIGINT NOT NULL REFERENCES ecommerce.products(product_id) ON DELETE CASCADE,
  user_id      BIGINT NOT NULL REFERENCES ecommerce.users(user_id) ON DELETE CASCADE,
  rating       SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title        VARCHAR(255),
  body         TEXT,
  is_approved  BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (product_id, user_id)
);

-- Indexes on addresses
CREATE INDEX idx_addresses_user_id ON ecommerce.addresses(user_id);

CREATE INDEX idx_addresses_is_default ON ecommerce.addresses(user_id, is_default);

-- Indexes on categories
CREATE INDEX idx_categories_parent_id ON ecommerce.categories(parent_id);

CREATE INDEX idx_categories_slug ON ecommerce.categories(slug);

-- Indexes on products
CREATE INDEX idx_products_category_id ON ecommerce.products(category_id);

CREATE INDEX idx_products_slug ON ecommerce.products(slug);

CREATE INDEX idx_products_is_active ON ecommerce.products(is_active);

CREATE INDEX idx_products_price ON ecommerce.products(price);

-- Indexes on product_images
CREATE INDEX idx_product_images_product_id ON ecommerce.product_images(product_id);

-- Indexes on carts
CREATE INDEX idx_carts_user_id ON ecommerce.carts(user_id);

CREATE INDEX idx_carts_session_id ON ecommerce.carts(session_id);

-- Indexes on cart_items
CREATE INDEX idx_cart_items_cart_id ON ecommerce.cart_items(cart_id);

CREATE INDEX idx_cart_items_product_id ON ecommerce.cart_items(product_id);

-- Indexes on orders
CREATE INDEX idx_orders_user_id ON ecommerce.orders(user_id);

CREATE INDEX idx_orders_status ON ecommerce.orders(status);

CREATE INDEX idx_orders_created_at ON ecommerce.orders(created_at DESC);

-- Indexes on order_items
CREATE INDEX idx_order_items_order_id ON ecommerce.order_items(order_id);

CREATE INDEX idx_order_items_product_id ON ecommerce.order_items(product_id);

-- Indexes on payments
CREATE INDEX idx_payments_order_id ON ecommerce.payments(order_id);

CREATE INDEX idx_payments_status ON ecommerce.payments(status);

-- Indexes on reviews
CREATE INDEX idx_reviews_product_id ON ecommerce.reviews(product_id);

CREATE INDEX idx_reviews_user_id ON ecommerce.reviews(user_id);

CREATE INDEX idx_reviews_rating ON ecommerce.reviews(rating);

-- Trigger function: auto-update updated_at
CREATE OR REPLACE FUNCTION ecommerce.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON ecommerce.users
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_addresses_updated_at
  BEFORE UPDATE ON ecommerce.addresses
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_categories_updated_at
  BEFORE UPDATE ON ecommerce.categories
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_products_updated_at
  BEFORE UPDATE ON ecommerce.products
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_carts_updated_at
  BEFORE UPDATE ON ecommerce.carts
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON ecommerce.orders
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_payments_updated_at
  BEFORE UPDATE ON ecommerce.payments
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

CREATE TRIGGER trg_reviews_updated_at
  BEFORE UPDATE ON ecommerce.reviews
  FOR EACH ROW EXECUTE FUNCTION ecommerce.set_updated_at();

-- View: product summary with avg rating
CREATE OR REPLACE VIEW ecommerce.v_product_summary AS
SELECT
  p.product_id,
  p.name,
  p.slug,
  p.price,
  p.stock_qty,
  p.is_active,
  c.name          AS category_name,
  ROUND(AVG(r.rating)::NUMERIC, 2) AS avg_rating,
  COUNT(r.review_id)               AS review_count
FROM ecommerce.products p
LEFT JOIN ecommerce.categories c ON c.category_id = p.category_id
LEFT JOIN ecommerce.reviews    r ON r.product_id  = p.product_id AND r.is_approved
GROUP BY p.product_id, p.name, p.slug, p.price, p.stock_qty, p.is_active, c.name;

-- View: order summary with user info and payment status
CREATE OR REPLACE VIEW ecommerce.v_order_summary AS
SELECT
  o.order_id,
  o.status        AS order_status,
  o.total,
  o.created_at    AS ordered_at,
  u.user_id,
  u.email,
  u.first_name,
  u.last_name,
  COUNT(oi.order_item_id) AS item_count,
  pay.status      AS payment_status,
  pay.method      AS payment_method
FROM ecommerce.orders o
JOIN ecommerce.users       u   ON u.user_id   = o.user_id
LEFT JOIN ecommerce.order_items oi  ON oi.order_id  = o.order_id
LEFT JOIN ecommerce.payments    pay ON pay.order_id  = o.order_id
GROUP BY o.order_id, o.status, o.total, o.created_at,
         u.user_id, u.email, u.first_name, u.last_name,
         pay.status, pay.method;

-- View: cart details with product info and line totals
CREATE OR REPLACE VIEW ecommerce.v_cart_details AS
SELECT
  c.cart_id,
  c.user_id,
  c.session_id,
  ci.cart_item_id,
  p.product_id,
  p.name          AS product_name,
  p.price         AS unit_price,
  ci.quantity,
  (p.price * ci.quantity) AS line_total
FROM ecommerce.carts      c
JOIN ecommerce.cart_items ci ON ci.cart_id    = c.cart_id
JOIN ecommerce.products   p  ON p.product_id  = ci.product_id;
