-- Food Booking App Schema: tables, indexes, functions, triggers, and views
-- Generated by PG AI Assistant on 2026-07-17 18:20:53 UTC
-- Contains: 54 DDL, 6 OTHER

CREATE SCHEMA IF NOT EXISTS food_booking;

CREATE TABLE food_booking.users (
    user_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(150)        NOT NULL,
    email         VARCHAR(255)        NOT NULL UNIQUE,
    phone         VARCHAR(20)         NOT NULL UNIQUE,
    password_hash TEXT                NOT NULL,
    is_active     BOOLEAN             NOT NULL DEFAULT TRUE,
    is_verified   BOOLEAN             NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.addresses (
    address_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id      BIGINT              NOT NULL REFERENCES food_booking.users(user_id) ON DELETE CASCADE,
    label        VARCHAR(50)         NOT NULL DEFAULT 'Home',
    address_line TEXT                NOT NULL,
    city         VARCHAR(100)        NOT NULL,
    state        VARCHAR(100)        NOT NULL,
    postal_code  VARCHAR(20)         NOT NULL,
    country      VARCHAR(100)        NOT NULL DEFAULT 'US',
    latitude     NUMERIC(9,6),
    longitude    NUMERIC(9,6),
    is_default   BOOLEAN             NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.restaurants (
    restaurant_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200)        NOT NULL,
    slug            VARCHAR(200)        NOT NULL UNIQUE,
    description     TEXT,
    email           VARCHAR(255)        NOT NULL UNIQUE,
    phone           VARCHAR(20)         NOT NULL,
    address_line    TEXT                NOT NULL,
    city            VARCHAR(100)        NOT NULL,
    state           VARCHAR(100)        NOT NULL,
    postal_code     VARCHAR(20)         NOT NULL,
    country         VARCHAR(100)        NOT NULL DEFAULT 'US',
    latitude        NUMERIC(9,6),
    longitude       NUMERIC(9,6),
    cuisine_type    VARCHAR(100),
    opening_time    TIME                NOT NULL DEFAULT '08:00:00',
    closing_time    TIME                NOT NULL DEFAULT '22:00:00',
    avg_rating      NUMERIC(3,2)        NOT NULL DEFAULT 0.00,
    is_active       BOOLEAN             NOT NULL DEFAULT TRUE,
    is_verified     BOOLEAN             NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.menus (
    menu_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT              NOT NULL REFERENCES food_booking.restaurants(restaurant_id) ON DELETE CASCADE,
    name          VARCHAR(150)        NOT NULL,
    description   TEXT,
    is_active     BOOLEAN             NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.menu_categories (
    category_id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    menu_id       BIGINT              NOT NULL REFERENCES food_booking.menus(menu_id) ON DELETE CASCADE,
    name          VARCHAR(150)        NOT NULL,
    description   TEXT,
    sort_order    INT                 NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.menu_items (
    item_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_id   BIGINT              NOT NULL REFERENCES food_booking.menu_categories(category_id) ON DELETE CASCADE,
    restaurant_id BIGINT              NOT NULL REFERENCES food_booking.restaurants(restaurant_id) ON DELETE CASCADE,
    name          VARCHAR(200)        NOT NULL,
    description   TEXT,
    price         NUMERIC(10,2)       NOT NULL CHECK (price >= 0),
    image_url     TEXT,
    is_vegetarian BOOLEAN             NOT NULL DEFAULT FALSE,
    is_vegan      BOOLEAN             NOT NULL DEFAULT FALSE,
    is_gluten_free BOOLEAN            NOT NULL DEFAULT FALSE,
    is_available  BOOLEAN             NOT NULL DEFAULT TRUE,
    sort_order    INT                 NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.coupons (
    coupon_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)         NOT NULL UNIQUE,
    description     TEXT,
    discount_type   VARCHAR(20)         NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    discount_value  NUMERIC(10,2)       NOT NULL CHECK (discount_value > 0),
    min_order_value NUMERIC(10,2)       NOT NULL DEFAULT 0.00,
    max_discount    NUMERIC(10,2),
    usage_limit     INT,
    used_count      INT                 NOT NULL DEFAULT 0,
    valid_from      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    valid_until     TIMESTAMPTZ         NOT NULL,
    is_active       BOOLEAN             NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.orders (
    order_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id           BIGINT              NOT NULL REFERENCES food_booking.users(user_id),
    restaurant_id     BIGINT              NOT NULL REFERENCES food_booking.restaurants(restaurant_id),
    address_id        BIGINT              NOT NULL REFERENCES food_booking.addresses(address_id),
    coupon_id         BIGINT              REFERENCES food_booking.coupons(coupon_id),
    status            VARCHAR(30)         NOT NULL DEFAULT 'pending'
                                          CHECK (status IN ('pending','confirmed','preparing','out_for_delivery','delivered','cancelled')),
    subtotal          NUMERIC(10,2)       NOT NULL DEFAULT 0.00,
    discount_amount   NUMERIC(10,2)       NOT NULL DEFAULT 0.00,
    delivery_fee      NUMERIC(10,2)       NOT NULL DEFAULT 0.00,
    tax_amount        NUMERIC(10,2)       NOT NULL DEFAULT 0.00,
    total_amount      NUMERIC(10,2)       NOT NULL DEFAULT 0.00,
    special_instructions TEXT,
    estimated_delivery_time TIMESTAMPTZ,
    delivered_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.order_items (
    order_item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id      BIGINT              NOT NULL REFERENCES food_booking.orders(order_id) ON DELETE CASCADE,
    item_id       BIGINT              NOT NULL REFERENCES food_booking.menu_items(item_id),
    item_name     VARCHAR(200)        NOT NULL,
    unit_price    NUMERIC(10,2)       NOT NULL,
    quantity      INT                 NOT NULL CHECK (quantity > 0),
    line_total    NUMERIC(10,2)       GENERATED ALWAYS AS (unit_price * quantity) STORED,
    special_notes TEXT,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.payments (
    payment_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id         BIGINT              NOT NULL REFERENCES food_booking.orders(order_id),
    payment_method   VARCHAR(50)         NOT NULL CHECK (payment_method IN ('credit_card','debit_card','paypal','wallet','cash_on_delivery')),
    status           VARCHAR(30)         NOT NULL DEFAULT 'pending'
                                         CHECK (status IN ('pending','completed','failed','refunded')),
    amount           NUMERIC(10,2)       NOT NULL,
    transaction_id   VARCHAR(255)        UNIQUE,
    paid_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.delivery_agents (
    agent_id      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(150)        NOT NULL,
    email         VARCHAR(255)        NOT NULL UNIQUE,
    phone         VARCHAR(20)         NOT NULL UNIQUE,
    vehicle_type  VARCHAR(50)         NOT NULL CHECK (vehicle_type IN ('bike','scooter','car','bicycle')),
    is_available  BOOLEAN             NOT NULL DEFAULT TRUE,
    is_active     BOOLEAN             NOT NULL DEFAULT TRUE,
    avg_rating    NUMERIC(3,2)        NOT NULL DEFAULT 0.00,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.deliveries (
    delivery_id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id          BIGINT              NOT NULL UNIQUE REFERENCES food_booking.orders(order_id),
    agent_id          BIGINT              REFERENCES food_booking.delivery_agents(agent_id),
    status            VARCHAR(30)         NOT NULL DEFAULT 'pending'
                                          CHECK (status IN ('pending','assigned','picked_up','on_the_way','delivered','failed')),
    picked_up_at      TIMESTAMPTZ,
    delivered_at      TIMESTAMPTZ,
    delivery_notes    TEXT,
    created_at        TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ         NOT NULL DEFAULT NOW()
);

CREATE TABLE food_booking.reviews (
    review_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id       BIGINT              NOT NULL REFERENCES food_booking.users(user_id),
    restaurant_id BIGINT              NOT NULL REFERENCES food_booking.restaurants(restaurant_id),
    order_id      BIGINT              NOT NULL REFERENCES food_booking.orders(order_id),
    rating        SMALLINT            NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment       TEXT,
    created_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, order_id)
);

CREATE TABLE food_booking.agent_reviews (
    agent_review_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id         BIGINT              NOT NULL REFERENCES food_booking.users(user_id),
    agent_id        BIGINT              NOT NULL REFERENCES food_booking.delivery_agents(agent_id),
    order_id        BIGINT              NOT NULL REFERENCES food_booking.orders(order_id),
    rating          SMALLINT            NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment         TEXT,
    created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, order_id)
);

-- Indexes on addresses
CREATE INDEX idx_addresses_user_id ON food_booking.addresses(user_id);

CREATE INDEX idx_addresses_is_default ON food_booking.addresses(user_id, is_default);

-- Indexes on restaurants
CREATE INDEX idx_restaurants_slug ON food_booking.restaurants(slug);

CREATE INDEX idx_restaurants_city ON food_booking.restaurants(city);

CREATE INDEX idx_restaurants_cuisine ON food_booking.restaurants(cuisine_type);

CREATE INDEX idx_restaurants_is_active ON food_booking.restaurants(is_active);

-- Indexes on menus
CREATE INDEX idx_menus_restaurant_id ON food_booking.menus(restaurant_id);

-- Indexes on menu_categories
CREATE INDEX idx_menu_categories_menu_id ON food_booking.menu_categories(menu_id);

-- Indexes on menu_items
CREATE INDEX idx_menu_items_category_id ON food_booking.menu_items(category_id);

CREATE INDEX idx_menu_items_restaurant_id ON food_booking.menu_items(restaurant_id);

CREATE INDEX idx_menu_items_is_available ON food_booking.menu_items(is_available);

CREATE INDEX idx_menu_items_price ON food_booking.menu_items(price);

-- Indexes on coupons
CREATE INDEX idx_coupons_code ON food_booking.coupons(code);

CREATE INDEX idx_coupons_valid_until ON food_booking.coupons(valid_until);

-- Indexes on orders
CREATE INDEX idx_orders_user_id ON food_booking.orders(user_id);

CREATE INDEX idx_orders_restaurant_id ON food_booking.orders(restaurant_id);

CREATE INDEX idx_orders_status ON food_booking.orders(status);

CREATE INDEX idx_orders_created_at ON food_booking.orders(created_at);

-- Indexes on order_items
CREATE INDEX idx_order_items_order_id ON food_booking.order_items(order_id);

CREATE INDEX idx_order_items_item_id ON food_booking.order_items(item_id);

-- Indexes on payments
CREATE INDEX idx_payments_order_id ON food_booking.payments(order_id);

CREATE INDEX idx_payments_status ON food_booking.payments(status);

-- Indexes on deliveries
CREATE INDEX idx_deliveries_agent_id ON food_booking.deliveries(agent_id);

CREATE INDEX idx_deliveries_status ON food_booking.deliveries(status);

-- Indexes on reviews
CREATE INDEX idx_reviews_restaurant_id ON food_booking.reviews(restaurant_id);

CREATE INDEX idx_reviews_user_id ON food_booking.reviews(user_id);

-- Reusable trigger function to auto-update updated_at
CREATE OR REPLACE FUNCTION food_booking.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON food_booking.users
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_addresses_updated_at
    BEFORE UPDATE ON food_booking.addresses
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_restaurants_updated_at
    BEFORE UPDATE ON food_booking.restaurants
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_menus_updated_at
    BEFORE UPDATE ON food_booking.menus
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_menu_categories_updated_at
    BEFORE UPDATE ON food_booking.menu_categories
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_menu_items_updated_at
    BEFORE UPDATE ON food_booking.menu_items
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_orders_updated_at
    BEFORE UPDATE ON food_booking.orders
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_payments_updated_at
    BEFORE UPDATE ON food_booking.payments
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_deliveries_updated_at
    BEFORE UPDATE ON food_booking.deliveries
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_reviews_updated_at
    BEFORE UPDATE ON food_booking.reviews
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

CREATE TRIGGER trg_coupons_updated_at
    BEFORE UPDATE ON food_booking.coupons
    FOR EACH ROW EXECUTE FUNCTION food_booking.set_updated_at();

-- Function to auto-update restaurant avg_rating after a review insert/update/delete
CREATE OR REPLACE FUNCTION food_booking.refresh_restaurant_rating()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    UPDATE food_booking.restaurants
    SET avg_rating = (
        SELECT COALESCE(AVG(rating), 0)
        FROM food_booking.reviews
        WHERE restaurant_id = COALESCE(NEW.restaurant_id, OLD.restaurant_id)
    )
    WHERE restaurant_id = COALESCE(NEW.restaurant_id, OLD.restaurant_id);
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_refresh_restaurant_rating
    AFTER INSERT OR UPDATE OR DELETE ON food_booking.reviews
    FOR EACH ROW EXECUTE FUNCTION food_booking.refresh_restaurant_rating();

-- Function to auto-update delivery agent avg_rating after an agent review insert/update/delete
CREATE OR REPLACE FUNCTION food_booking.refresh_agent_rating()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    UPDATE food_booking.delivery_agents
    SET avg_rating = (
        SELECT COALESCE(AVG(rating), 0)
        FROM food_booking.agent_reviews
        WHERE agent_id = COALESCE(NEW.agent_id, OLD.agent_id)
    )
    WHERE agent_id = COALESCE(NEW.agent_id, OLD.agent_id);
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_refresh_agent_rating
    AFTER INSERT OR UPDATE OR DELETE ON food_booking.agent_reviews
    FOR EACH ROW EXECUTE FUNCTION food_booking.refresh_agent_rating();

-- View: restaurant summary with avg rating and total orders
CREATE OR REPLACE VIEW food_booking.v_restaurant_summary AS
SELECT
    r.restaurant_id,
    r.name,
    r.slug,
    r.cuisine_type,
    r.city,
    r.avg_rating,
    COUNT(DISTINCT o.order_id)  AS total_orders,
    COUNT(DISTINCT rv.review_id) AS total_reviews,
    r.is_active,
    r.opening_time,
    r.closing_time
FROM food_booking.restaurants r
LEFT JOIN food_booking.orders o ON o.restaurant_id = r.restaurant_id
LEFT JOIN food_booking.reviews rv ON rv.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id;

-- View: order summary with user, restaurant, payment and delivery info
CREATE OR REPLACE VIEW food_booking.v_order_summary AS
SELECT
    o.order_id,
    u.full_name        AS customer_name,
    u.email            AS customer_email,
    r.name             AS restaurant_name,
    o.status           AS order_status,
    o.subtotal,
    o.discount_amount,
    o.delivery_fee,
    o.tax_amount,
    o.total_amount,
    p.payment_method,
    p.status           AS payment_status,
    d.status           AS delivery_status,
    da.full_name       AS delivery_agent,
    o.created_at
FROM food_booking.orders o
JOIN food_booking.users u ON u.user_id = o.user_id
JOIN food_booking.restaurants r ON r.restaurant_id = o.restaurant_id
LEFT JOIN food_booking.payments p ON p.order_id = o.order_id
LEFT JOIN food_booking.deliveries d ON d.order_id = o.order_id
LEFT JOIN food_booking.delivery_agents da ON da.agent_id = d.agent_id;

-- View: menu item details with category and restaurant info
CREATE OR REPLACE VIEW food_booking.v_menu_item_details AS
SELECT
    mi.item_id,
    r.name             AS restaurant_name,
    m.name             AS menu_name,
    mc.name            AS category_name,
    mi.name            AS item_name,
    mi.description,
    mi.price,
    mi.is_vegetarian,
    mi.is_vegan,
    mi.is_gluten_free,
    mi.is_available
FROM food_booking.menu_items mi
JOIN food_booking.menu_categories mc ON mc.category_id = mi.category_id
JOIN food_booking.menus m ON m.menu_id = mc.menu_id
JOIN food_booking.restaurants r ON r.restaurant_id = mi.restaurant_id;
